const mongoose = require("mongoose");

const LabSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },

  email: {
    type: String,
    required: true,
    unique: true,
  },

  password: {
    type: String,
    required: true,
  },

  phone: {
    type: String,
    required: true,
  },

  address: {
    type: String,
    required: true,
  },

  role: {
    type: String,
    enum: ['lab'],
    default: 'lab'
  },

  clinicId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Clinic",
    required: true,
  },

  // approved: {
  //   type: Boolean,
  //   default: false,
  // },


  clinicApproved: {
  type: Boolean,
  default: false,
},

adminApproved: {
  type: Boolean,
  default: false,
},

 lastLogin: Date,
  patients: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: "Patient"
  }],

  // Available diagnostic tests
 availableTests: [
  {
    name: { type: String, required: true },
    cost: { type: Number, required: true },
    department: { type: String, required: true },
    description: { type: String, required: true },
    normalRange: { type: String, required: true }, // Add this line
  }
],
  // Test reports generated by this lab
  testReports: [{
    patientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Patient"
    },
    testName: String,
    result: String,
    normalRange: String,
    uploadedAt: {
      type: Date,
      default: Date.now
    },
    fileUrl: String // URL to PDF/image report
  }],

  // Prescriptions for which this lab handles diagnostic tests
  prescriptions: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: "Prescription"
  }],

  // Bills generated by lab
  bills: [{
    amount: Number,
    description: String,
    patientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Patient"
    },
    paid: {
      type: Boolean,
      default: false
    },
    generatedAt: {
      type: Date,
      default: Date.now
    }
  }],

  // Payments received by lab
  payments: [{
    patientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Patient"
    },
    amount: Number,
    method: {
      type: String,
      enum: ["cash", "card", "online"]
    },
    status: {
      type: String,
      enum: ["paid", "pending", "failed"],
      default: "pending"
    },
    paidAt: Date
  }],

  notifications: [{
    message: String,
    type: {
      type: String,
      enum: ["info", "alert", "report"],
      default: "info"
    },
    createdAt: {
      type: Date,
      default: Date.now
    }
  }],

  lastLogin: {
    type: Date
  },

  isActive: {
    type: Boolean,
    default: true
  },

  createdAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model("Lab", LabSchema);












// const mongoose = require("mongoose");

// const LabSchema = new mongoose.Schema({
//   name: { type: String, required: true },

//   email: { type: String, required: true, unique: true },

//   password: { type: String, required: true },

//   phone: { type: String, required: true },

//   address: { type: String, required: true },

//   role: { type: String, enum: ["lab"], default: "lab" },

//   clinicId: { type: mongoose.Schema.Types.ObjectId, ref: "Clinic", required: true },

//   clinicApproved: { type: Boolean, default: false },

//   adminApproved: { type: Boolean, default: false },

//   lastLogin: Date,

//   patients: [{ type: mongoose.Schema.Types.ObjectId, ref: "Patient" }],

//   availableTests: [
//     {
//       name: { type: String, required: true },
//       cost: { type: Number, required: true },
//       description: { type: String },
//       department: { type: String },
//     },
//   ],

//   testReports: [
//     {
//       patientId: { type: mongoose.Schema.Types.ObjectId, ref: "Patient" },
//       testName: String,
//       result: String,
//       normalRange: String,
//       uploadedAt: { type: Date, default: Date.now },
//       fileUrl: String,
//     },
//   ],

//   prescriptions: [{ type: mongoose.Schema.Types.ObjectId, ref: "Prescription" }],

//   bills: [
//     {
//       amount: Number,
//       description: String,
//       patientId: { type: mongoose.Schema.Types.ObjectId, ref: "Patient" },
//       paid: { type: Boolean, default: false },
//       generatedAt: { type: Date, default: Date.now },
//     },
//   ],

//   payments: [
//     {
//       patientId: { type: mongoose.Schema.Types.ObjectId, ref: "Patient" },
//       amount: Number,
//       method: { type: String, enum: ["cash", "card", "online"] },
//       status: { type: String, enum: ["paid", "pending", "failed"], default: "pending" },
//       paidAt: Date,
//     },
//   ],

//   notifications: [
//     {
//       message: String,
//       type: { type: String, enum: ["info", "alert", "report"], default: "info" },
//       createdAt: { type: Date, default: Date.now },
//     },
//   ],

//   isActive: { type: Boolean, default: true },

//   createdAt: { type: Date, default: Date.now },
// });

// module.exports = mongoose.model("Lab", LabSchema);
